name:                sdlyampa
version:             1.0.0.0
github:              "https://github.com/rottensunday/Haskell_Projekt_Yampa"
license:             BSD3
author:              "Aleksander Wisniewski"
maintainer:          "arnachimm@gmail.com"
copyright:           "Aleksander Wisniewski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "Opis tutaj: <https://github.com/rottensunday/Haskell_Projekt_Yampa/blob/master/README.md>"

dependencies:
- base >= 4.7 && < 5
- sdl2
- Yampa
- linear
- sdl2-ttf
- text
- simple-affine-space
- htiled
- containers
- mtl
- time
- lens
- directory
- split

library:
  source-dirs: src

executables:
  sdlyampa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdlyampa

tests:
  sdlyampa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdlyampa
